name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.7'
      - name: Install dev dependencies
        run: |
          poetry install --only lint
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.7'
      - name: Install dev dependencies
        run: |
          poetry install --with test
      - name: Run Pytest
        run: |
          poetry run pytest
